CREATE TABLE currency (
    CURRENCY_ID INT AUTO_INCREMENT PRIMARY KEY,
    CURRENCY_CODE NVARCHAR(5) UNIQUE NOT NULL,
    CURRENCY_NAME NVARCHAR(10) NOT NULL
);

INSERT INTO currency (CURRENCY_CODE, CURRENCY_NAME) VALUES ('USD', '美元');
INSERT INTO currency (CURRENCY_CODE, CURRENCY_NAME) VALUES ('GBP', '英鎊');
INSERT INTO currency (CURRENCY_CODE, CURRENCY_NAME) VALUES ('EUR', '歐元');
